travis:
  secure:
    BINSTAR_TOKEN: m7ClLiO6TQzBgcfLO9ZIfuDkALhKw1aZbqQQIbDypSEgXqD9ZeZnHvk4xZ2RpvJ6/nGgba6zJMceCcO47iObFjpzMsSBDfUfcnA8JVYn7LjGmEGGiGudvRKZP6GgeJDlffk0NPGc/jUSQcvU4i+Q1j/yaoE57IuSUHhL/odwZJBTdPnugpcx5OuVEqilsAnT4s+iD4V5z+LjgkRdZO4/mrGoY9o+E0Oj5pV84kMSwuV1XECJTUPXbAx2TfiiR92dGCT7eWiNhxCPsswS3KhNB2fobKo3R63P4UgsQF0jKmwNLM6IGpxrGYRT+x+5kjhgLno32xPuWU1WPR85V39V/zfr2T2PxhWTVVBC1iPeToor3qjEnF6vHNtFQSr8g+7rbippzVjkpCRZkHNzKTAunAVO521iYdsR/W4gDCH/s92kA+lFs5s/UiiWqYV/HCEa8FXvI83qQLVcQoOpV5X4nsLnZ6d1LDex28JAbYUvzz1RG6rR4O1gErqK38kF5jo2phJvznGaCM5Tm44m1bU+nCXoYuwUd8I+zppGH9I5A2nKrIleG+RbTkMrVd276cjYx9PPPPEEQMk3brH5w+0nzF+2p8TVUkq/kKz2+OPguGbctL0LEJuB76IyB//wSFufcJ3/l0aeExv08z5esvuNsslJ7tP5+ZbbwPL5JECcinY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
