travis:
  secure:
    BINSTAR_TOKEN: JTJCqyunHUDkkhlHx+iV8r1n/3pslN0M/A54GJpFUb+5maBglsGX5WcJek3dVPU+B5tZnmVknzfL1qnz+ixJHktiTTcdfmVV2YbzS/KXFztv/l1HigsRTLyrYV0lf2Z+bOpYQpPF2sz4dorUsZQOgx2gKJelfDpPSpq8XupCpYQEDzFZJHRz7DwcW3UdvS+TpQ4N86BABnuFBPlvL4ZfFxcRuhasjC52/0kMMzFQwtWswcvBRMjv7re1/ytMByvoh79i/gWAO/x/N5c6tve5yHlJzi6hkO172M5gkPWbLCffDdYkINLt9l+GVDfs3SVV5r+vxvtTXAWzFLbpuT82pzCofBSLCRXJb5tyyTBSmThMbFFqBfAFnR5KYBsdISVCznFmhpH6wOpmkcWdrnixzq6pV2AFTlDrqi5BgxuB7v3NcGLN+mNnDMH1/wwy+ZTaNTU61jErWCO1bDCjYsppMUqeIdNl/eg76QERifWAijdFhctePSVX/zONyZ4ZRVszVXtqOaWl+EbFFgrkOeFMJaJzm7hbS5vrWgmrV2GG76Qt/FyM51lyzRMKP7cVAiSxrrD0sZ60jn58y0ANOvAGKBzBgjO75FUGwqpBke+LecnbSgmez+5lEEK1qh6os0XZikdP6DyXQOW7XJ9sbYhk20RjYyXKoWyDRb/LWXE/jYE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
